---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:
    - name: make continous deployment to server
      git:
              repo: 'https://github.com/samsonmuoki/Django-PollsApp.git'
              dest: muoki/
    # - name: installing requirements
    #   pip:
    #     requirements: /home/sam/muoki/pollsapp/requirements.txt
    #     virtualenv: /home/sam/muoki/venv
    #     virtualenv_python: python3.6



    - name: activate venv and make migrations
      shell: |
        . /home/sam/muoki/venv/bin/activate
        pip3 install -r /home/sam/muoki/pollsapp/requirements.txt
        python3 /home/sam/muoki/pollsapp/manage.py migrate
    
    - name: start gunicorn
      shell: |
        . /home/sam/muoki/venv/bin/activate
        cd /home/sam/muoki/pollsapp
        gunicorn --daemon --workers 3 --bind unix:/home/sam/muoki/pollsapp/pollsapp.sock pollsapp.wsgi
          

