---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: True

  tasks:

          - name: add universe repository for bionic
            apt_repository: 
              repo: deb http://archive.ubuntu.com/ubuntu bionic universe
              state: present
            when: ansible_distribution_release == 'bionic'
  
          - name: Install base packages
            apt: 
              name: "{{ packages }}"
            vars:
              packages:
                - locales
                - build-essential
                - htop
                - git
                - python3-apt
                - python3-pip
                - supervisor
                - redis-server
                        
          # - name: Upgrade pip
          #   pip: name=pip state=latest
            
          - name: Create directory chat_app
            file:
              state: directory
              path: chat_app
          
          - name: Pull project from github
            git:
              repo: 'https://github.com/samsonmuoki/django-channels-tutorial.git'
              dest: chat_app/

          # - name: stop supervisor
          #   service:
          #     name: supervisor
          #     state: stopped
          
          - name: Install setuptools
            pip:
              name: setuptools
              executable: pip3
          
          # INSTALLING VIRTUALENV, CREATING A VIRTUAL ENVIRONMENT AND INSTALLING
          # REQUIREMENTS ONLY NEED TO BE RUN THE FIRST TIME WHEN SETTING UP THE SERVER

          - name: install virtualenv
            pip: 
              name: virtualenv
              executable: pip3
            become: yes
            become_user: root              
          
          - name: create virtualenv
            command: /usr/local/bin/virtualenv chat_app/venv
            
          - name: installing requirements
            pip:
              requirements: /home/sam/chat_app/main_requirements.txt
              virtualenv: /home/sam/chat_app/venv
              virtualenv_python: python3.6

          # RUN ABOVE COMMANDS THE FIRST TIME ONLY WHEN SETTING UP THE SERVER

          - name: activate venv and make migrations
            shell: |
              . /home/sam/chat_app/venv/bin/activate
              python3 /home/sam/chat_app/manage.py migrate

          - name: Recursively change ownership of chat_app directory
            file:
              path: /home/sam/chat_app/channels_tutorial
              state: directory
              recurse: yes
              owner: sam
